## Create a new user 
POST  http://localhost:3000/auth/signup
content-type: application/json

{
    "email":"test@example.com",
    "password": "test0000"
}


### find a particular user
GET http://localhost:3000/auth/3

### find all users with a given email
GET http://localhost:3000/auth?email=test@example.com

### Delete a user
DELETE http://localhost:3000/auth/2

### Update a user
PATCH http://localhost:3000/auth/3
content-type: application/json

{
    "email":"sara❤️@example.com"
}

